/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTermsRouteImport } from './routes/_authenticated/terms'
import { Route as AuthenticatedProvidersListRouteImport } from './routes/_authenticated/providers-list'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNegotiationsRouteImport } from './routes/_authenticated/negotiations'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFaqRouteImport } from './routes/_authenticated/faq'
import { Route as AuthenticatedDisclosureRouteImport } from './routes/_authenticated/disclosure'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedControlRouteImport } from './routes/_authenticated/control'
import { Route as AuthenticatedBusinessPaymentProcessingRouteImport } from './routes/_authenticated/business-payment-processing'
import { Route as AuthenticatedBusinessOnboardingRouteImport } from './routes/_authenticated/business-onboarding'
import { Route as AuthenticatedBusinessDashboardRouteImport } from './routes/_authenticated/business-dashboard'
import { Route as AuthenticatedBankGuideRouteImport } from './routes/_authenticated/bank-guide'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedAddChargeRouteImport } from './routes/_authenticated/add-charge'
import { Route as AuthenticatedNegotiationIdRouteImport } from './routes/_authenticated/negotiation.$id'
import { Route as AuthenticatedConfirmIdRouteImport } from './routes/_authenticated/confirm.$id'
import { Route as AuthenticatedNegotiationIdOffersRouteImport } from './routes/_authenticated/negotiation.$id.offers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTermsRoute = AuthenticatedTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersListRoute =
  AuthenticatedProvidersListRouteImport.update({
    id: '/providers-list',
    path: '/providers-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegotiationsRoute =
  AuthenticatedNegotiationsRouteImport.update({
    id: '/negotiations',
    path: '/negotiations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaqRoute = AuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisclosureRoute = AuthenticatedDisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlRoute = AuthenticatedControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessPaymentProcessingRoute =
  AuthenticatedBusinessPaymentProcessingRouteImport.update({
    id: '/business-payment-processing',
    path: '/business-payment-processing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessOnboardingRoute =
  AuthenticatedBusinessOnboardingRouteImport.update({
    id: '/business-onboarding',
    path: '/business-onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardRoute =
  AuthenticatedBusinessDashboardRouteImport.update({
    id: '/business-dashboard',
    path: '/business-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankGuideRoute = AuthenticatedBankGuideRouteImport.update({
  id: '/bank-guide',
  path: '/bank-guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddChargeRoute = AuthenticatedAddChargeRouteImport.update({
  id: '/add-charge',
  path: '/add-charge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegotiationIdRoute =
  AuthenticatedNegotiationIdRouteImport.update({
    id: '/negotiation/$id',
    path: '/negotiation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfirmIdRoute = AuthenticatedConfirmIdRouteImport.update({
  id: '/confirm/$id',
  path: '/confirm/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegotiationIdOffersRoute =
  AuthenticatedNegotiationIdOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedNegotiationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/add-charge': typeof AuthenticatedAddChargeRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/bank-guide': typeof AuthenticatedBankGuideRoute
  '/business-dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business-onboarding': typeof AuthenticatedBusinessOnboardingRoute
  '/business-payment-processing': typeof AuthenticatedBusinessPaymentProcessingRoute
  '/control': typeof AuthenticatedControlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disclosure': typeof AuthenticatedDisclosureRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/negotiations': typeof AuthenticatedNegotiationsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/providers-list': typeof AuthenticatedProvidersListRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/confirm/$id': typeof AuthenticatedConfirmIdRoute
  '/negotiation/$id': typeof AuthenticatedNegotiationIdRouteWithChildren
  '/negotiation/$id/offers': typeof AuthenticatedNegotiationIdOffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/add-charge': typeof AuthenticatedAddChargeRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/bank-guide': typeof AuthenticatedBankGuideRoute
  '/business-dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business-onboarding': typeof AuthenticatedBusinessOnboardingRoute
  '/business-payment-processing': typeof AuthenticatedBusinessPaymentProcessingRoute
  '/control': typeof AuthenticatedControlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disclosure': typeof AuthenticatedDisclosureRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/negotiations': typeof AuthenticatedNegotiationsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/providers-list': typeof AuthenticatedProvidersListRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/confirm/$id': typeof AuthenticatedConfirmIdRoute
  '/negotiation/$id': typeof AuthenticatedNegotiationIdRouteWithChildren
  '/negotiation/$id/offers': typeof AuthenticatedNegotiationIdOffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/add-charge': typeof AuthenticatedAddChargeRoute
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/bank-guide': typeof AuthenticatedBankGuideRoute
  '/_authenticated/business-dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/_authenticated/business-onboarding': typeof AuthenticatedBusinessOnboardingRoute
  '/_authenticated/business-payment-processing': typeof AuthenticatedBusinessPaymentProcessingRoute
  '/_authenticated/control': typeof AuthenticatedControlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disclosure': typeof AuthenticatedDisclosureRoute
  '/_authenticated/faq': typeof AuthenticatedFaqRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/negotiations': typeof AuthenticatedNegotiationsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/providers-list': typeof AuthenticatedProvidersListRoute
  '/_authenticated/terms': typeof AuthenticatedTermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/confirm/$id': typeof AuthenticatedConfirmIdRoute
  '/_authenticated/negotiation/$id': typeof AuthenticatedNegotiationIdRouteWithChildren
  '/_authenticated/negotiation/$id/offers': typeof AuthenticatedNegotiationIdOffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add-charge'
    | '/affiliate'
    | '/bank-guide'
    | '/business-dashboard'
    | '/business-onboarding'
    | '/business-payment-processing'
    | '/control'
    | '/dashboard'
    | '/disclosure'
    | '/faq'
    | '/leaderboard'
    | '/negotiations'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/providers-list'
    | '/terms'
    | '/auth/callback'
    | '/confirm/$id'
    | '/negotiation/$id'
    | '/negotiation/$id/offers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/add-charge'
    | '/affiliate'
    | '/bank-guide'
    | '/business-dashboard'
    | '/business-onboarding'
    | '/business-payment-processing'
    | '/control'
    | '/dashboard'
    | '/disclosure'
    | '/faq'
    | '/leaderboard'
    | '/negotiations'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/providers-list'
    | '/terms'
    | '/auth/callback'
    | '/confirm/$id'
    | '/negotiation/$id'
    | '/negotiation/$id/offers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add-charge'
    | '/_authenticated/affiliate'
    | '/_authenticated/bank-guide'
    | '/_authenticated/business-dashboard'
    | '/_authenticated/business-onboarding'
    | '/_authenticated/business-payment-processing'
    | '/_authenticated/control'
    | '/_authenticated/dashboard'
    | '/_authenticated/disclosure'
    | '/_authenticated/faq'
    | '/_authenticated/leaderboard'
    | '/_authenticated/negotiations'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/privacy'
    | '/_authenticated/profile'
    | '/_authenticated/providers-list'
    | '/_authenticated/terms'
    | '/auth/callback'
    | '/_authenticated/confirm/$id'
    | '/_authenticated/negotiation/$id'
    | '/_authenticated/negotiation/$id/offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/terms': {
      id: '/_authenticated/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers-list': {
      id: '/_authenticated/providers-list'
      path: '/providers-list'
      fullPath: '/providers-list'
      preLoaderRoute: typeof AuthenticatedProvidersListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negotiations': {
      id: '/_authenticated/negotiations'
      path: '/negotiations'
      fullPath: '/negotiations'
      preLoaderRoute: typeof AuthenticatedNegotiationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faq': {
      id: '/_authenticated/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthenticatedFaqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disclosure': {
      id: '/_authenticated/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof AuthenticatedDisclosureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control': {
      id: '/_authenticated/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof AuthenticatedControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-payment-processing': {
      id: '/_authenticated/business-payment-processing'
      path: '/business-payment-processing'
      fullPath: '/business-payment-processing'
      preLoaderRoute: typeof AuthenticatedBusinessPaymentProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-onboarding': {
      id: '/_authenticated/business-onboarding'
      path: '/business-onboarding'
      fullPath: '/business-onboarding'
      preLoaderRoute: typeof AuthenticatedBusinessOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-dashboard': {
      id: '/_authenticated/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/business-dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank-guide': {
      id: '/_authenticated/bank-guide'
      path: '/bank-guide'
      fullPath: '/bank-guide'
      preLoaderRoute: typeof AuthenticatedBankGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-charge': {
      id: '/_authenticated/add-charge'
      path: '/add-charge'
      fullPath: '/add-charge'
      preLoaderRoute: typeof AuthenticatedAddChargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negotiation/$id': {
      id: '/_authenticated/negotiation/$id'
      path: '/negotiation/$id'
      fullPath: '/negotiation/$id'
      preLoaderRoute: typeof AuthenticatedNegotiationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confirm/$id': {
      id: '/_authenticated/confirm/$id'
      path: '/confirm/$id'
      fullPath: '/confirm/$id'
      preLoaderRoute: typeof AuthenticatedConfirmIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negotiation/$id/offers': {
      id: '/_authenticated/negotiation/$id/offers'
      path: '/offers'
      fullPath: '/negotiation/$id/offers'
      preLoaderRoute: typeof AuthenticatedNegotiationIdOffersRouteImport
      parentRoute: typeof AuthenticatedNegotiationIdRoute
    }
  }
}

interface AuthenticatedNegotiationIdRouteChildren {
  AuthenticatedNegotiationIdOffersRoute: typeof AuthenticatedNegotiationIdOffersRoute
}

const AuthenticatedNegotiationIdRouteChildren: AuthenticatedNegotiationIdRouteChildren =
  {
    AuthenticatedNegotiationIdOffersRoute:
      AuthenticatedNegotiationIdOffersRoute,
  }

const AuthenticatedNegotiationIdRouteWithChildren =
  AuthenticatedNegotiationIdRoute._addFileChildren(
    AuthenticatedNegotiationIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddChargeRoute: typeof AuthenticatedAddChargeRoute
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedBankGuideRoute: typeof AuthenticatedBankGuideRoute
  AuthenticatedBusinessDashboardRoute: typeof AuthenticatedBusinessDashboardRoute
  AuthenticatedBusinessOnboardingRoute: typeof AuthenticatedBusinessOnboardingRoute
  AuthenticatedBusinessPaymentProcessingRoute: typeof AuthenticatedBusinessPaymentProcessingRoute
  AuthenticatedControlRoute: typeof AuthenticatedControlRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisclosureRoute: typeof AuthenticatedDisclosureRoute
  AuthenticatedFaqRoute: typeof AuthenticatedFaqRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNegotiationsRoute: typeof AuthenticatedNegotiationsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProvidersListRoute: typeof AuthenticatedProvidersListRoute
  AuthenticatedTermsRoute: typeof AuthenticatedTermsRoute
  AuthenticatedConfirmIdRoute: typeof AuthenticatedConfirmIdRoute
  AuthenticatedNegotiationIdRoute: typeof AuthenticatedNegotiationIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddChargeRoute: AuthenticatedAddChargeRoute,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedBankGuideRoute: AuthenticatedBankGuideRoute,
  AuthenticatedBusinessDashboardRoute: AuthenticatedBusinessDashboardRoute,
  AuthenticatedBusinessOnboardingRoute: AuthenticatedBusinessOnboardingRoute,
  AuthenticatedBusinessPaymentProcessingRoute:
    AuthenticatedBusinessPaymentProcessingRoute,
  AuthenticatedControlRoute: AuthenticatedControlRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisclosureRoute: AuthenticatedDisclosureRoute,
  AuthenticatedFaqRoute: AuthenticatedFaqRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNegotiationsRoute: AuthenticatedNegotiationsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProvidersListRoute: AuthenticatedProvidersListRoute,
  AuthenticatedTermsRoute: AuthenticatedTermsRoute,
  AuthenticatedConfirmIdRoute: AuthenticatedConfirmIdRoute,
  AuthenticatedNegotiationIdRoute: AuthenticatedNegotiationIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
